### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [uasoft-indonesia/badaso#1010]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@scgajge12) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by scgajge12** [comment]
Hi hello.

The email address for my GitHub account is below.
- morioka1831@gmail.com   

<br>

Also, regarding the "SECURITY.md" file, I would like to ask you to create one.
Please describe the following two points.
- Supported Versions
- Reporting a Vulnerability

If you don't mind, please use Hunrt for communication.

Thank you very much.

**Comment by rizkiheryandi** [comment]
Hello @psmoros 

Here's https://github.com/uasoft-indonesia/badaso/blob/main/SECURITY.md

Thanks in advance
