### ISSUE TITLE
New project installed with version 2.9.4 and not the last one 2.9.8

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#1018]
I installed a fresh new badaso project and got the version 2.9.4 but saw that the last version is 2.9.8.
My php version is the last one 8.2.8.

Not confident with my composer knowledge I asked for help on so that confirms a problem

https://stackoverflow.com/questions/76849216/how-to-upgrade-to-the-last-version-of-a-package/76851328#76851328

**Comment by Dri372** [comment]
Does not work on my host (Ubuntu 22 - Php 8.2.8)

composer create-project badaso/starter test
cd test
cat composer.lock | grep -A1 badaso/core
            "name": "badaso/core",
            "version": "**2.9.4"**,
composer require badaso/core -W
cat composer.lock | grep -A1 badaso/core
            "name": "badaso/core",
            "version": "**2.9.4**",

**Comment by rahmatalmubarak** [comment]
For now, you can install badaso with _curl -s "https://badaso-starter.uatech.co.id/your-project-name" | bash_

**Comment by Dri372** [comment]
Thank for your reply, for now I don't need the very last version, this issue is for your information, but if I use the previous command I get the following error :+1: 

```
Migrated:  2019_12_14_000001_create_personal_access_tokens_table (10.03ms)

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [Database\Seeders\Badaso\BadasoSeeder] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:879
```

**Comment by hasbullah-mughniy** [comment]
Same here, Cannot install the latest version

**Comment by Dri372** [comment]
@hasbullah-mughniy 

What version? Now it works for me with version 2.9.10

**Comment by Dri372** [comment]
It works for me with version 2.9.10

**Comment by hasbullah-mughniy** [comment]
> It works for me with version 2.9.10

It works but installed with laravel version 8, not 9

**Comment by Dri372** [comment]
Same for me, that's I open the #1046
