### ISSUE TITLE
GetData.php - ERROR: in_array(): Argument #2 ($haystack) must be of type array, null given

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#1019]
**Describe the bug**
After an **upgrade**, you cannot browse an existing crud, you get an error "ERROR: in_array(): Argument #2 ($haystack) must be of type array, null given {"userId":1,"exception":"[object] (TypeError(code: 0): in_array(): Argument #2 ($haystack) must be of type array, null given at /var/www/html/Badaso/t1p/vendor/badaso/core/src/Helpers/GetData.php:344"

**Root cause**
in the table badaso_permissions, the fields "roles_can_see_all_data" and "field_identify_related_user" are Null.

**To Reproduce**
- update a project ( 2.5.2 to 2.9.4 in my case)
- you can simulate the same error by setting Null to these 2 fields for a table in a new project.

**Badaso (please complete the following information):**
 - Version 2.5.2 to 2.9.4

**Comment by rizkiheryandi** [comment]
it fixed on newest version
