### ISSUE TITLE
Badaso Dashboard Cannot Open In Ios Below 16.6

### ISSUE THREAD

**Issue by rizqisyah** [uasoft-indonesia/badaso#1025]
**Describe the bug**
Badaso Dashboard Cannot Open In Ios Below 16.6

**To Reproduce**
Go to https://badaso-demo.uatech.co.id/dashboard/login)

**Expected behavior**
User Can Login And Show Box

**Screenshots**
https://ibb.co/jTxFYvB

**Badaso (please complete the following information):**
 - Version [e.g. 2.9.4]

**Smartphone (please complete the following information):**
 - Device: iPhone 11,11Pro,13,12
 - OS: iOS 16.1,15
 - Browser Safari
 - Version 16,15
 -

**Comment by mascang** [comment]
@rizqisyah kemungkinan ini disebabkan oleh regex lookbehind assertion di bagian https://github.com/uasoft-indonesia/badaso/blob/d7d6616981e2d646d4867bb1817e85d684df3aca/src/resources/badaso/pages/home.vue#L40 

support di safari browser baru diterapkan mulai versi 16.4, merujuk ke laman mdn web docs di https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion

Laman login dapat ditampilkan di safari browser dengan menghilangkan bagian  (?<!\.\d*).  Saya belum dapat menemukan case dimana lookbehind dibutuhkan pada contoh demo

**Comment by rizkiheryandi** [comment]
@rizqisyah please update your safari browser to 16.4 as @mascang explanation, thanks !
