### ISSUE TITLE
Can't login in first time

### ISSUE THREAD

**Issue by pandigresik** [uasoft-indonesia/badaso#1037]
**Describe the bug**
Can't login to dashboard because data from redis always null

**To Reproduce**
1. Go to 'login page'
2. Fill username and password
3. Click Login
4. See error on notification **Call to a member function where() on bool**

**Expected behavior**

**Screenshots**

[Screencast from 29-09-23 09:53:18.webm](https://github.com/uasoft-indonesia/badaso/assets/1853475/c75b46aa-aaa5-49ab-abc0-961e45966c82)

**Badaso (please complete the following information):**
 - Version 2.9.9

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome
 - Version 117.0.5938.88 (Build Resmi) (64 bit)

**Smartphone (please complete the following information):**

**Additional context**
Configuration data from redis always return false, because there is proses to save configuration to redis on first time application running. I'am install using composer follow step in https://badaso-docs.uatech.co.id/getting-started/installation

**Comment by Dri372** [comment]
Same for version 2.9.10
