### ISSUE TITLE
Error when trying to rename a menu item.

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#1040]
- Badaso 2.9.4

- When I edit a menu item on my Prod app, I get an infinite popup "Loading"

- Root cause in file vendor/badaso/core/src/resources/js/pages/menu-management/builder.vue

typo error in lines marked //eslint : is -> this

**Comment by miftahurrahmi** [comment]
Please send a video recording of the error you have experienced. Just for your information, Badaso has released version 2.9.10

**Comment by Dri372** [comment]
Same type error in version 2.9.10

**Comment by miftahurrahmi** [comment]
https://github.com/uasoft-indonesia/badaso/assets/60600153/33bcfb13-d850-4454-b37f-2f80caf6f0b0

Our team did not encounter any issues as you described

**Comment by miftahurrahmi** [comment]
Our internal team has checked it and did not find any issues as you mentioned

**Comment by Dri372** [comment]
Create a new project : composer create-project badaso/starter p1

Check the file : vendor/badaso/core/src/resources/js/pages/menu-management/builder.vue

Line 331 : title: **is**.$t("alert.danger"),

**Comment by miftahurrahmi** [comment]
We were not aware that you were using Badaso Core through the Badaso Starter composer. After our team checked, we found that Badaso Starter is still using an outdated version of Badaso Core. We have fixed it, and the latest version of the Badaso Starter composer will be released soon.

Thank you for your enthusiasm in using Badaso.
