### ISSUE TITLE
Installation error @OA/PathItem

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_20210621_222532_623.jpg](https://user-images.githubusercontent.com/25028868/122787627-b61fa800-d2df-11eb-9e8e-ff1be2a5475a.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by belutz** [comment]
![image](https://user-images.githubusercontent.com/12677557/122845140-38828900-d32d-11eb-89e0-d875d2741739.png)
**Desktop** 
OS: Win10 20H2
Wamp: Laragon 5.0.0 21053 (php 7.4.19)
npm: 6.14.8
node: 14.15.1
laravel: 8.0(fresh install)

stuck on
i just install new laravel (8.0) and then install badaso, but that error appear
`php artisan badaso:setup`

**Comment by aditya5660** [comment]
i have same issues , are you have done with this issues? @rizkiheryandi

**Comment by rizkiheryandi** [comment]
> i have same issues , are you have done with this issues? @rizkiheryandi 

Fixed on latest release, please update.

Thank you 😊
