### ISSUE TITLE
[ Error Badaso Setup ] - Couldn't find constant L5_SWAGGER_CONST_HOST,

### ISSUE THREAD

**Issue by aditya5660** [uasoft-indonesia/badaso#197]
**Describe the bug**
I just fresh installed Laravel version v8.48.0 with `laravel new app-name`

Then run

- `composer require uasoft-indonesia/badaso`
- `php artisan badaso:setup`
- 

**Screenshots**
![image](https://user-images.githubusercontent.com/35070884/123044020-54685680-d423-11eb-824b-05f1d6b33edc.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Teminal : iterm2
 - Composer Version : 2
 - Laravel Version : 8.48
 - Badaso Version : 2.0.0-rc.5

**Comment by rizkiheryandi** [comment]
Fixed on lates release, please update, thank you 😊
