### ISSUE TITLE
eroor installation Illuminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#202]
**Screenshots**
![image](https://user-images.githubusercontent.com/12677557/123202100-2e53bc80-d4de-11eb-83b5-37d2829e1575.png)

Desktop
OS: Win10 20H2
Wamp: Laragon 5.0.0 21053 (php 7.4.19)
npm: 6.14.8
node: 14.15.1
laravel: 8.0(fresh install)
badaso 2.0.0-rc.6

stuck on
i just install new laravel (8.0) and then install badaso 2.0.0-rc.6 , but that error appear
`php artisan db:seed --class=BadasoSeeder`

**Comment by my4fdal** [comment]
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/12677557/123202100-2e53bc80-d4de-11eb-83b5-37d2829e1575.png)
> 
> Desktop
> OS: Win10 20H2
> Wamp: Laragon 5.0.0 21053 (php 7.4.19)
> npm: 6.14.8
> node: 14.15.1
> laravel: 8.0(fresh install)
> badaso 2.0.0-rc.6
> 
> stuck on
> i just install new laravel (8.0) and then install badaso 2.0.0-rc.6 , but that error appear
> `php artisan db:seed --class=BadasoSeeder`

try again with command `php artisan db:seed --class=Database\Seeders\Badaso\BadasoSeeder`

**Comment by rizkiheryandi** [comment]
On laravel 8, you need include the namespace to call class on subfolder @belutz

**Comment by rizkiheryandi** [comment]
we already update the documentation too

sorry for the wrong documentation
