### ISSUE TITLE
Not Stable, file not found etc

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#208]
some time after refresh or logout from another tab will appear this view, then after refresh again normal again
![image](https://user-images.githubusercontent.com/12677557/123566450-f1433f00-d7e9-11eb-9de2-2f24ca8c7b2d.png)
![image](https://user-images.githubusercontent.com/12677557/123566669-6dd61d80-d7ea-11eb-8742-48c7b14a98f6.png)

Desktop
OS: Win10 20H2
Wamp: Laragon 5.0.0 21053 (php 7.4.19)
npm: 6.14.8
node: 14.15.1
laravel: 8.0(fresh install)

**Comment by dannyatthaya** [comment]
Can you provide video/screen-record about the problem?

**Comment by belutz** [comment]
https://user-images.githubusercontent.com/12677557/123632696-6e020780-d842-11eb-8a9e-a9e450e45d6e.mp4

**Comment by dannyatthaya** [comment]
Hi @belutz, this issue has been fixed on PR #213. Thanks for your contribution.
