### ISSUE TITLE
Bug update image

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#209]
after upload/ just select  image in filemanager always not found
![image](https://user-images.githubusercontent.com/12677557/123568026-a62b2b00-d7ed-11eb-9937-cc7004cca12d.png)
![image](https://user-images.githubusercontent.com/12677557/123568086-c9ee7100-d7ed-11eb-9d17-5f1b50dffc55.png)
![image](https://user-images.githubusercontent.com/12677557/123568103-d377d900-d7ed-11eb-978d-986def1e937f.png)
![image](https://user-images.githubusercontent.com/12677557/123568115-d83c8d00-d7ed-11eb-8f42-5eb1f81ea287.png)

Desktop
OS: Win10 20H2
Wamp: Laragon 5.0.0 21053 (php 7.4.19)
npm: 6.14.8
node: 14.15.1
laravel: 8.0(fresh install)

**Comment by dannyatthaya** [comment]
It's strange. It look like the image return the wrong path. Have you ever been upgrade the badaso before? If so, please run the following command `php artisan badaso:setup --force`. If you encounter another issue/problem after running the command, please reply this issue.

**Comment by belutz** [comment]
![image](https://user-images.githubusercontent.com/12677557/123633048-e4066e80-d842-11eb-9ed2-8c7d00c373c9.png)
![image](https://user-images.githubusercontent.com/12677557/123633038-e072e780-d842-11eb-8c22-a319f18d48f0.png)
still not found

**Comment by dannyatthaya** [comment]
You need to install laravel 8 as a new one with new badaso too. I guess that you upgrade badaso version from previous version. In badaso current version, user default avatar value is `files/shares/default-user.png`.
