### ISSUE TITLE
Can't access media assets

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#225]
You need to install laravel 8 as a new one with new badaso too. I guess that you upgrade badaso version from previous version. In badaso current version, user default avatar value is `files/shares/default-user.png`.

_Originally posted by @dannyatthaya in https://github.com/uasoft-indonesia/badaso/issues/209#issuecomment-870339281_

**Comment by belutz** [comment]
this is my specification 
**Desktop**
OS: Win10 20H2
Wamp: Laragon 5.0.0 21053 (php 7.4.19)
npm: 6.14.8
node: 14.15.1
laravel: 8.0(fresh install)
![image](https://user-images.githubusercontent.com/12677557/123936435-6025c100-d9bf-11eb-924f-136f7e941855.png)

i using laravel 8.0, when i using laravel 5.x always error, doesn't meet recruitment

**Comment by rizkiheryandi** [comment]
Have you tried create new laravel 8 project again and install badaso on there ? because badaso still now release the stable version, so each RC release may had many changes that can break previous release (need deeper knowledge of badaso structure to upgrade manually)

And please use :
node 12.16.x
npm 6.13.x
yarn 1.22.x

Thanks

**Comment by rizkiheryandi** [comment]
Also change your filesystem to public on .env @belutz 

`FILESYSTEM_DRIVER=public`

**Comment by belutz** [comment]
> Hi @belutz
> 
> Have you tried re-create new laravel 8 project and install badaso on there ? because badaso still not release the stable version, so each RC release may had many changes that can break previous release (need deeper knowledge of badaso structure to upgrade manually)
> 
> Use this version as docs mentioned :
> 
> * node 12.16.x
> * npm 6.13.x
> * yarn 1.22.x
> 
> Thanks

![image](https://user-images.githubusercontent.com/12677557/124046904-30b59980-da3d-11eb-936e-d761ba9e6e6f.png)

**Comment by rizkiheryandi** [comment]
Hello, sorry i dont get the point about your latest reply, can you explain more detail please ? @belutz
