### ISSUE TITLE
Hi @belutz, this issue has been fixed on PR #213. Thanks for your contribution.

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#227]
Hi @belutz, this issue has been fixed on PR #213. Thanks for your contribution.

_Originally posted by @dannyatthaya in https://github.com/uasoft-indonesia/badaso/issues/208#issuecomment-870406770_

**Comment by belutz** [comment]
still appear
![image](https://user-images.githubusercontent.com/12677557/124049164-15995880-da42-11eb-8b22-e4a3d0d39d41.png)

**Comment by dannyatthaya** [comment]
Hei @belutz, could you provide us with some screenshot of your `.env` and your `badaso.php` config. Thanks

**Comment by rizkiheryandi** [comment]
Hi @belutz , this issue fix on latest release, please update, thanks :)
