### ISSUE TITLE
Separate setting CRUD management betwwen "basic setting" and "advance setting"

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso#297]
**Is your feature request related to a problem? Please describe.**
Need simplecity setting and don't confuse new user

**Describe the solution you'd like**
Just show basic setting first, and hide advance setting (model & controller override, etc) on a expansion panel

**Describe alternatives you've considered**
We can use expansion panel or anything for hide expansion panel, just choose the better one

**Comment by aqidd** [comment]
Suggestion: this should be the basic settings while the others are advanced settings

![image](https://user-images.githubusercontent.com/1284186/128117058-7e8212fa-2029-4ae7-beac-36445f1bec7c.png)

This also should be all checked by default
![image](https://user-images.githubusercontent.com/1284186/128117098-886d1390-b5fe-4a5a-a05f-04f55319f695.png)
