### ISSUE TITLE
Informational dashboard

### ISSUE THREAD

**Issue by aqidd** [uasoft-indonesia/badaso#300]
**Is your feature request related to a problem? Please describe.**
Currently, Badaso dashboard UI is lacking information for early adopters

**Describe the solution you'd like**
Add extra information in dashboard

**Describe alternatives you've considered**
Borrowing from other open source projects:

Strapi has this helpful information on their dashboard
![image](https://user-images.githubusercontent.com/1284186/128117766-65d41ad8-f83e-403c-949c-350c1bfdf1b3.png)

There should be help icon for some complex/new concept/badaso exclusive feature
![image](https://user-images.githubusercontent.com/1284186/128117910-3964777f-404f-4ab2-803e-85c20c1dd9f1.png)

**Comment by rizkiheryandi** [comment]
Btw i think we need the second one "icon help"

But for the first one "Strapi has this helpful information on their dashboard", badaso users can read it on github pages / badaso docs. Badaso already show the widget at homepage
