### ISSUE TITLE
Create CRUD bug using SQLite

### ISSUE THREAD

**Issue by aqidd** [uasoft-indonesia/badaso#327]
**Describe the bug**
Cannot create proper CRUD

**To Reproduce**
1. Create table
2. Create CRUD with default values
3. Edit CRUD
4. All CRUD fields are unchecked

**Expected behavior**
CRUD fields are checked according to step 2

**Screenshots**
![image](https://user-images.githubusercontent.com/1284186/129453667-30435a79-01b0-46d2-b1fe-566de581c73a.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version: rc13

**Comment by dannyatthaya** [comment]
Hi @aqidd, could you provide us with some screenshot from the console.

**Comment by aqidd** [comment]
Sure thing. Here are more details:

- Tried this again with rc14
- sqlite as database

console error:
![image](https://user-images.githubusercontent.com/1284186/130467947-3b2e763b-cccf-4a8c-8d62-cf0cbb1bf6cf.png)

here's the return from api:
```
{"message":"Request was successful","errors":null,"data":{"crud":{"id":2,"name":"tbltest","slug":"tbltest","displayNameSingular":"Tbltest","displayNamePlural":"Tbltest","icon":null,"modelName":null,"policyName":null,"controller":null,"orderColumn":null,"orderDisplayColumn":null,"orderDirection":null,"generatePermissions":"1","serverSide":"0","isMaintenance":"0","description":null,"details":null,"notification":"[]","isSoftDelete":"0","createdAt":"2021-08-23T14:46:55.000000Z","updatedAt":"2021-08-23T14:46:55.000000Z","dataRows":[{"id":6,"dataTypeId":"2","field":"id","type":"number","displayName":"Id","required":"1","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"1"},{"id":7,"dataTypeId":"2","field":"intest","type":"number","displayName":"Intest","required":"1","browse":"1","read":"1","edit":"1","add":"1","delete":"1","details":"{}","relation":null,"order":"2"},{"id":8,"dataTypeId":"2","field":"txtest","type":"textarea","displayName":"Txtest","required":"1","browse":"1","read":"1","edit":"1","add":"1","delete":"1","details":"{}","relation":null,"order":"3"},{"id":9,"dataTypeId":"2","field":"created_at","type":"datetime","displayName":"Created At","required":"0","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"4"},{"id":10,"dataTypeId":"2","field":"updated_at","type":"datetime","displayName":"Updated At","required":"0","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"5"}]}}}
```

and here's the crud status (intest and txtest should all be selected)
![image](https://user-images.githubusercontent.com/1284186/130468249-9feef342-a14d-42b4-b63e-999c50978897.png)

**Comment by rizkiheryandi** [comment]
I just wonder, how about using mysql as database mr @aqidd ?

Is it working with mysql ?

thank you

**Comment by aqidd** [comment]
you're right @rizkiheryandi , this only happens using SQLite. MySQL works without any problems. 

I changed the issue title for clarity

**Comment by Messhias** [comment]
> Sure thing. Here are more details:
> 
> * Tried this again with rc14
> * SQLite as database
> 
> console error: ![image](https://user-images.githubusercontent.com/1284186/130467947-3b2e763b-cccf-4a8c-8d62-cf0cbb1bf6cf.png)
> 
> here's the return from API:
> 
> ```
> {"message":"Request was successful","errors":null,"data":{"crud":{"id":2,"name":"tbltest","slug":"tbltest","displayNameSingular":"Tbltest","displayNamePlural":"Tbltest","icon":null,"modelName":null,"policyName":null,"controller":null,"orderColumn":null,"orderDisplayColumn":null,"orderDirection":null,"generatePermissions":"1","serverSide":"0","isMaintenance":"0","description":null,"details":null,"notification":"[]","isSoftDelete":"0","createdAt":"2021-08-23T14:46:55.000000Z","updatedAt":"2021-08-23T14:46:55.000000Z","dataRows":[{"id":6,"dataTypeId":"2","field":"id","type":"number","displayName":"Id","required":"1","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"1"},{"id":7,"dataTypeId":"2","field":"intest","type":"number","displayName":"Intest","required":"1","browse":"1","read":"1","edit":"1","add":"1","delete":"1","details":"{}","relation":null,"order":"2"},{"id":8,"dataTypeId":"2","field":"txtest","type":"textarea","displayName":"Txtest","required":"1","browse":"1","read":"1","edit":"1","add":"1","delete":"1","details":"{}","relation":null,"order":"3"},{"id":9,"dataTypeId":"2","field":"created_at","type":"datetime","displayName":"Created At","required":"0","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"4"},{"id":10,"dataTypeId":"2","field":"updated_at","type":"datetime","displayName":"Updated At","required":"0","browse":"1","read":"1","edit":"0","add":"0","delete":"0","details":"{}","relation":null,"order":"5"}]}}}
> ```
> 
> and here's the crud status (interest and txtest should all be selected) ![image](https://user-images.githubusercontent.com/1284186/130468249-9feef342-a14d-42b4-b63e-999c50978897.png)

As per what I checked it seems you not having a response, did you check if your SQLite database and tables were created?

Also, it's good to try to use nullasafe operator to avoid issues with undefined returns in javascript.

**Comment by rizkiheryandi** [comment]
@my4fdal also need PR for v3.x
