### ISSUE TITLE
where are files generated?

### ISSUE THREAD

**Issue by sanjaylama** [uasoft-indonesia/badaso#343]
Looks promising.
I just generated a CRUD for a simple table. 
But when I go to laravel project and locate controller, model, routes and vue js view files, I could not find any of the files (though system was running).
Where are those files generated? inside vendor?
Does it follow normal laravel vue structure?

**Comment by dannyatthaya** [comment]
Hi @sanjaylama, thanks for curious about Badaso. That's how magic is works hehehe ;).







Just kidding. Badaso didn't generate any files (Model, Controller, Vue.js view). Instead, badaso use dynamic base model, base controller and vue.js view for CRUD generated.

**Comment by rizkiheryandi** [comment]
@sanjaylama you can asking more at https://github.com/uasoft-indonesia/badaso/discussions 

Thanks

**Comment by sanjaylama** [comment]
Ok. 
But I think I have got my answer and it does not seem to generate any file.
If it does not then it may be problematic to use these in bigger system.

The structure is great but rather than inventing custom and own ways if you just automate the vue js + laravel CRUD generation (like https://github.com/InfyOmLabs but which lacks vue part) generating the necessary files, just making task easier, it will have greater potential and popular.
just a suggestion. Looks good but can be great.
