### ISSUE TITLE
yarn dev after secondly run after install is error

### ISSUE THREAD

**Issue by ceceps** [uasoft-indonesia/badaso#385]
**Describe the bug**
Error when run `yarn dev` after second execution  

**To Reproduce**
my setup
- Ubuntu 20.0.4
- node : 14.17.6
- npm : 7.24.6
- yarn: 1.22.10

1. composer create-project badaso/starter crm_proj
2. yarn
3. yarn dev
 Install on first `yarn dev` it's successful but has the warning `no exit code`
4. console exit 
5. php artisan serve 
5. ctrl+ c ( to stop server)
6. yarn dev (second execution), has error below

```bash
$ yarn dev
yarn run v1.22.10
$ npm run development

> development
> mix


✖ Mix
  Compiled with some errors in 11.31s

ERROR in ./node_modules/canvg/lib/index.es.js 1933:16-23
Module not found: Error: Can't resolve 'process/browser' in '/home/ceceps/docker/apache-php7.4-portal/htdocs/crm_proj/node_modules/canvg/lib'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
error Command failed with exit code 1.
```

**Expected behavior**
 run smooth with laravel mix successfull message 

**Screenshots**
![Screenshot from 2021-09-25 20-12-22](https://user-images.githubusercontent.com/1675115/134772828-6b91370b-4895-4e35-866f-accca11a35de.png)

**Comment by rizkiheryandi** [comment]
Refference Note for contributor :

- https://github.com/laravel-mix/laravel-mix/issues/2737

**Comment by ceceps** [comment]
@rizkiheryandi 
i had add this script on `webpack.mix.js`
```js
mix.options({
    legacyNodePolyfills: true
});
````
compile mix is success build but strange badaso dashboard apps cannot login and the post theme module is blank, 
at login, it redirected to not found route.

if remove that line again and compile but with has an error `process/browser`, the apps can show and login as usually

**Comment by rizkiheryandi** [comment]
@ceceps 

Dont neet to add `egacyNodePolyfills: false` 

You can just ignore the error on yarn / npm log for now, because badaso still running as usually, but for sure we will try to fix it soon.

**Comment by musfandi** [comment]
any fix update

**Comment by rizkiheryandi** [comment]
need to find the better library replacement or waiting for the update #430

**Comment by rizkiheryandi** [comment]
To fix this issue, you can update the jsPDF module to latest version https://github.com/parallax/jsPDF/releases/tag/v2.4.0
