### ISSUE TITLE
jsPDF cause the `process/browser` error

### ISSUE THREAD

**Issue by dannyatthaya** [uasoft-indonesia/badaso#430]
**Describe the bug**
[jsPDF](https://github.com/parallax/jsPDF) from parallax is causing the error `process/browser` from using `canvg` library.

**Expected behavior**
Use another pdf generator library

**Comment by ceceps** [comment]
How about replace jsPDF with http://pdfkit.org/

**Comment by dannyatthaya** [comment]
I'll look into it

**Comment by rizkiheryandi** [comment]
To fix this issue, just update the jsPDF to the latest version https://github.com/parallax/jsPDF/releases/tag/v2.4.0

we can run `npm update`
