### ISSUE TITLE
Need performance improvement on maintenance system

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso#446]
**Is your feature request related to a problem? Please describe.**
Maintenance request is slower frontend page transition

**Describe the solution you'd like**
1. Redis integration and make the loading popup show up before system request the maintenance api
2. Get maintenance data direct to database (not via API)
3. Maintenance data based on .env not database

**Comment by afdal-develop** [comment]
(v) solusi 1 : 
	1. query maintenen ke database di gantikan ke redis
		flow : 
			1. ketika ubah config maintenen simpan ke redis data maintenen dari database
			2. ketika request ambil dari redis
	
	2. loading di mulai pada saat request maintenen

solusi 2 : 
	1. maintenen dengan middleware langsung ke database
	
solusi 3 : 
	1. maintenen dengan env
