### ISSUE TITLE
Problem runing first migrate with sql server database

### ISSUE THREAD

**Issue by ezalorpro** [uasoft-indonesia/badaso#483]
**Describe the bug**
Error while runing:  php artisan migrate when the database is microsoft sql server

**To Reproduce**
Run php artisan migrate with a microsoft sql server database

**Expected behavior**
the migrations should run properly

**Screenshots**
![image](https://user-images.githubusercontent.com/37134637/143312738-c7a09969-03f3-404c-bb30-57f829e7fb36.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- php version: 8
- badaso/core: ^2.0

**Additional context**

The problems since to be the cycles paths of on delete cascade or something like that.

**Comment by rizkiheryandi** [comment]
Fix with latest PR
