### ISSUE TITLE
Override Controller

### ISSUE THREAD

**Issue by rizqisyah** [uasoft-indonesia/badaso#504]
**Describe the bug**
If I Want Override Controller in my new menu, my new menu get label error

**To Reproduce**
1. Create Table
2. Create Crud Management
3. Create New Controller(I follow step from tutorial)
4. Copy Name newControoler to Advanced Setting(Controoler Name) i naming App\Http\Controller\NewController

**Expected behavior**
i can override controller

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser Firefox
 - Version 95

**Comment by rizkiheryandi** [comment]
Could you share the error please ? with screenshot is better too

Thank you

**Comment by rizqisyah** [comment]
![index](https://user-images.githubusercontent.com/32996501/147354148-cb0cbd51-7a24-4e3f-8120-aacff86a9f9d.jpg)
Error After I follow over ride controller from documentation

**Comment by rizqisyah** [comment]
![Uploading index.jpg…]()

**Comment by rizqisyah** [comment]
![index](https://user-images.githubusercontent.com/32996501/147354272-bb73f422-d8df-489a-98e8-e2112f57f89d.jpg)

**Comment by rizqisyah** [comment]
why closed ?

**Comment by rizkiheryandi** [comment]
![image](https://user-images.githubusercontent.com/25028868/147379812-12479bf5-78da-4e60-8e3f-f96f0ac1d3cf.png)

You closed it by yourself sir, why asking others instead 🧐

**Comment by rizqisyah** [comment]
lol sorry sir :D

**Comment by suseno1988** [comment]
How to close this issue, im some problem into override controller

**Comment by rizqisyah** [comment]
follow tutorial one on one and dont typo

Pada tanggal Kam, 17 Feb 2022 05.01, Suseno ***@***.***>
menulis:
