### ISSUE TITLE
Wrong link to the doc in badaso-dashboard/database/add

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#511]
**Describe the bug**
The link is : https://badaso-docs.uatech.co.id/docs/en/core-concept/database-management/
-> Page not found

**To Reproduce**
Fresh install of Badaso

**Expected behavior**
Good link
https://badaso-docs.uatech.co.id/core-concept/database-management

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Firefox
 - Version 96

**Comment by rizkiheryandi** [comment]
Could you explain more detail how to reproduce please ? 

thank you

**Comment by Dri372** [comment]
The wrong link (https://badaso-docs.uatech.co.id/docs/en/core-concept/database-management/) is in this file : 

vendor/badaso/core/src/resources/js/pages/database-management/add.vue
