### ISSUE TITLE
Class "Redis" not found 

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#513]
Each request conducts to this msg in the logs
Class "Redis" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"Redis\" not found at /users/philippe/st_p1_p3_p4/Laravel8/Badaso/badaso3/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:75) 

OS : Ubuntu 20

Solution
in config/database.php
replace
        'client' => env('REDIS_CLIENT', 'phpredis'),
by
        'client' => env('REDIS_CLIENT', 'predis'),

**Comment by rizkiheryandi** [comment]
yese, that's why in "php artisan badaso:setup" it will add key "REDIS_CLIENT" with "predis", because we using predis

**Comment by Dri372** [comment]
Ok, but you have to do a little updae on you install doc https://badaso-docs.uatech.co.id/getting-started/installation

"php artisan badaso:setup" to be done also in fresh install

**Comment by rizkiheryandi** [comment]
No need @Dri372 , badaso starter already updated
