### ISSUE TITLE
Error with Postgresql data type "character varying(...)"

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#542]
**Describe the bug**
When a (existing) table contains a field character varying(...) , it's impossible to modify it, to create a crud; ...

**To Reproduce**
CREATE TABLE test(f1 varchar(16));

**Comment by rahmatalmubarak** [comment]
I already try it myself, it's worked 

you should make sure the field type in crud management is relevant with field data type in the table. If the datatype is varchar, so make sure you use "text" field in crud management.
