### ISSUE TITLE
Error Crud 

### ISSUE THREAD

**Issue by belutz** [uasoft-indonesia/badaso#549]
**Describe the bug**
Error Crud 

**To Reproduce**
1.  add Crud to table
2. create crud
3. error danger in inspect element (_admin/v1/crud/add_)
![image](https://user-images.githubusercontent.com/12677557/153552879-45bee2a6-bc78-4405-9768-37c82902e3c1.png)

`{"data":null,"message":"Undefined array key \"field\"","errors":[{"file":"\/var\/www\/html\/guest_house\/vendor\/badaso\/core\/src\/Helpers\/ApiDocs.php","line":335,"function":"handleError","class":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/badaso\/core\/src\/Controllers\/BadasoCRUDController.php","line":492,"function":"getStub","class":"Uasoft\\Badaso\\Helpers\\ApiDocs","type":"::"},{"file":"\/var\/www\/html\/guest_house\/vendor\/badaso\/core\/src\/Controllers\/BadasoCRUDController.php","line":386,"function":"generateAPIDocs","class":"Uasoft\\Badaso\\Controllers\\BadasoCRUDController","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php","line":54,"function":"add","class":"Uasoft\\Badaso\\Controllers\\BadasoCRUDController","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php","line":45,"function":"callAction","class":"Illuminate\\Routing\\Controller","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php","line":262,"function":"dispatch","class":"Illuminate\\Routing\\ControllerDispatcher","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php","line":205,"function":"runController","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":721,"function":"run","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":128,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/badaso\/core\/src\/Middleware\/BadasoCheckPermissions.php","line":24,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Uasoft\\Badaso\\Middleware\\BadasoCheckPermissions","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/badaso\/core\/src\/Middleware\/ApiRequest.php","line":70,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Uasoft\\Badaso\\Middleware\\ApiRequest","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":723,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":698,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":662,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":651,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":167,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":128,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php","line":31,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php","line":40,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TrimStrings","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php","line":27,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php","line":86,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php","line":38,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Fruitcake\\Cors\\HandleCors","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/fideloper\/proxy\/src\/TrustProxies.php","line":57,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":142,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/var\/www\/html\/guest_house\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":111,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"\/var\/www\/html\/guest_house\/public\/index.php","line":52,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}]}`

**Screenshots**
![image](https://user-images.githubusercontent.com/12677557/153552293-f6e2ff4a-88b8-4001-a13f-e53bd5dc76ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser Chrome
 - Version 98

**Comment by rizkiheryandi** [comment]
Make sure your laravel project writeable by web server user, eg www-data ,  if you using nginx
