### ISSUE TITLE
Upload gambar problem

### ISSUE THREAD

**Issue by suseno1988** [uasoft-indonesia/badaso#555]
Saat upload gambar profil terjadi error danger di popup media manajer, file gambar terupload hanya tidak tampil 
Ini berlaku di semua tipe file upload

![FB_IMG_1645048559016](https://user-images.githubusercontent.com/59343663/154364014-2608cc58-ded0-4460-a489-394a70051d0e.jpg)

**Comment by rahmatalmubarak** [comment]
bisakah kamu cantumkan gambar yang lebih jelas karena tidak kelihatan, dan cantum kan juga screenshoot untuk tap network pada developer tool

**Comment by suseno1988** [comment]
![image](https://user-images.githubusercontent.com/59343663/154433076-9fd171d9-5a23-4b98-b9dd-1aaec3416d8e.png)
ini mas, saat upload error tapi file tersimpan

**Comment by suseno1988** [comment]
![image](https://user-images.githubusercontent.com/59343663/154433275-005ed8b8-f4ba-4fcb-9dee-e9ec7f31ec3e.png)
mengubah url storage/storage jadi storage/ aja dimana mas
soalnya di filenya masuk
![image](https://user-images.githubusercontent.com/59343663/154433534-d4fd2eca-ea5c-45b4-b0a0-840a3687b5b8.png)

**Comment by suseno1988** [comment]
![image](https://user-images.githubusercontent.com/59343663/154444829-665b0cce-9cb3-4f0d-aa69-83f11a169ba4.png)

ini permasalahan hanya ada di load gambar di lfm File manajer saat field di crud manajer memilih tipe single upload/multiple upload

klo untuk media manajer bawaan sudah berfungsi

**Comment by rizkiheryandi** [comment]
We can't reproduce the error, maybe you can try explain the error more detail

i think you can make sure the permission of your folder is readable and writeable by the web server user if you using linux

**Comment by deanddy** [comment]
Hi. I have the same error as you. the image is already uploaded to project folder, but it didnt show up in app (invalid upload request) I hope this will fixed soon. cc @rizkiheryandi .

![image](https://user-images.githubusercontent.com/46615273/154926888-294a9c5d-13c3-4763-ad16-dd4669bcb7cc.png)

**Comment by abayzv** [comment]
> Hi. I have the same error as you. the image is already uploaded to project folder, but it didnt show up in app (invalid upload request) I hope this will fixed soon. cc @rizkiheryandi .
> 
> ![image](https://user-images.githubusercontent.com/46615273/154926888-294a9c5d-13c3-4763-ad16-dd4669bcb7cc.png)

just change the config in config/lfm.php
search "should_create_thumbnails" , then change the value to false

**Comment by rizkiheryandi** [comment]
it's looks like the error just happened on Windows OS, i can't reproduce it on linux 

our team will try to test it on windows soon

**Comment by rizkiheryandi** [comment]
The problem is, make sure the FILESYSTEM_DRIVER key on .env has "public" value if you using local system 

FILESYSTEM_DRIVER=public

Please read the installation documentation carefullly later.

**Comment by deanddy** [comment]
> The problem is, make sure the FILESYSTEM_DRIVER key on .env has "public" value if you using local system
> 
> FILESYSTEM_DRIVER=public
> 
> Please read the installation documentation carefullly later.

Thank you !

**Comment by perfectminor** [comment]
Hello @rizkiheryandi @rahmatalmubarak @abayzv , I've read this issue from the beginning of the page, but I haven't found a solution even though I've tried "just change the configuration in config/lfm.php
search for "should_create_thumbnails", then change the value to false" and also I have checked the ".env" file, from the beginning it already has a public value. And I have also changed the public value in the manual version of badaso.

Note: Badaso V 2.4.8 with Windows Operating System

![Capture1](https://user-images.githubusercontent.com/89902438/158339084-8185d8d9-f4a0-40bb-b5f3-9c4950f3f38d.PNG)
![Capture2](https://user-images.githubusercontent.com/89902438/158339096-9c26cb6d-5f53-48ed-ba56-6c637ab06921.PNG)
![Capture3](https://user-images.githubusercontent.com/89902438/158339102-61c36940-6dd0-46d4-8049-dc95287a433f.PNG)

**Comment by rizkiheryandi** [comment]
@perfectminor yes it's still a known issue for thumbnails in windows OS, so you can disable the thumb for now in windows OS

btw, you can also use docker instead of using windows local system, it's better i think

**Comment by Nemure231** [comment]
Have same problem in windows with composer instalation, but i figured it out. This cause when you already run storage link `php artisan storage:link` then i the same time you maybe change Badaso basic config (for example 'badaso-dashboard' to something else). The storage link might still keep Badaso base config.

What you need to do is simply just delete the storage link file in public folder, and then run `php artisan storage:link` again.
