### ISSUE TITLE
Search with blank

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#571]
**Description**
When you enter a search with a blank, ie : text1 text2 , search is done on "text1 text2" that's sound goog but it's not the "classical" way.

**-a- Describe the solution you'd like**
Search enter : "text1 text2" -> search "text1 text2" as actual
Search enter : text1 tex2 -> search text1 AND text2

**-b-Even better solution**
Accept simple logic in the search enter, ie
Search enter : text1 -OR- text2 -> search text1 OR text2

**-a- Idea of solution**
in vendor/badaso/core/src/resources/js/components/BadasoTable.vue
```
    getItemsSearch(min, max) {
      const search = this.normalize(this.searchx);
      const searchs = search.split(" ");
      return this.sortItems(this.data)
        .filter((tr) => {
                let res=true;
                searchs.forEach ( search => {
                        res= res && ( this.normalize(this.getValues(tr).toString()).indexOf(search) != -1 );
                })
                return ( res );
        })
```
```
    queriedResults() {
      let queriedResults = this.data;
      if (this.searchx && this.search) {
        let searchs = this.searchx.split(" "); 
        let dataBase = this.data;
        queriedResults = dataBase.filter((tr) => {
          let values = this.getValues(tr)
            .toString()
            .toLowerCase();
          let res=true;                               
          searchs.forEach ( search => {
                res= res && ( values.indexOf(search.toLowerCase()) != -1 );
          });
          return ( res );
        });
      }
      return queriedResults;
    },
```
Note : Should be probably good to have the previous code in a common method (no duplicate code)

**Comment by rizkiheryandi** [comment]
I think you can create a PR for this, so we can try your solution, thank you

**Comment by Dri372** [comment]
Should be possible.

But first can you remove your duplicate code (code the search in only one place), or explain why it's not your solution?

Then I propose, if your are ok, the following search : 
- "t1t2 ... tn" or 't1 t2 ... tn' -> t1 t2 ... tn
- t1 t2 ... tn -> t1 AND t2 ... AND tn
- AND(t1 t2 ... tn) -> t1 AND t2 ... AND tn
- OR(t1 t2 ... tn) -> t1 OR t2  ... OR tn
- later it should be probably useful to allow NOT before t1, t2, ..., tn

**Comment by rizkiheryandi** [comment]
Could you give a demonstrate with real case keywords ? maybe with smartphone or laptop things ? so i can understand it better

you can also provide a screenshot or some visualitation also if posibble

or some refference from another link too that we can test 

thanks in advance

**Comment by Dri372** [comment]
Let's imagine a table 'cars' with 3 fields model, power, color
m1; 50 ; Black
m1 ; 50 ; Red
m2 ; 50 ; Black
m2; 60 : Green

With the actual Seacrh, it's not possible to list all black cars of 50 kW 
With the proposed modif if you enter in the Search "50 Black" (or Black 50) you'll get the answer : 
m1; 50 ; Black
m2 ; 50 ; Black
