### ISSUE TITLE
wrong image url in wyswyg with s3 storage

### ISSUE THREAD

**Issue by abayzv** [uasoft-indonesia/badaso#575]
the s3 storage is working properly
then i try to upload image in code editor in CRUD, its working fine, but when i save the data, the image is gone wrong path

**Comment by rizkiheryandi** [comment]
could you provide more detail explanation please, what is the current path and the expected path

**Comment by abayzv** [comment]
I found the problem
the problem is the wyswyg upload file is to "storage/files" folder, not to "storage/photos" folder
I forgot to add permissions to the "storage/files" folder
