### ISSUE TITLE
File Manager Image Not Found

### ISSUE THREAD

**Issue by getheboxs** [uasoft-indonesia/badaso#577]
**Describe the bug**
the image does not appear in the file manager, after inspection it turns out that there is a duplicate directory "storage"

**To Reproduce**
1. Go to 'profile'
2. Click on 'avatar'
3. See image error

**Expected behavior**
wrong image address
http://127.0.0.1:8000/storage/storage/photos/1/thumbs/3777370.jpg
correct image address
http://127.0.0.1:8000/storage/photos/1/thumbs/3777370.jpg

**Screenshots**
![Capture](https://user-images.githubusercontent.com/2411316/155269893-1a64739f-957e-47c3-9388-651342735e4b.JPG)

**Comment by rizkiheryandi** [comment]
Duplicate issue #555 

I guess you used windows os, you can try the temporary solution by @abayzv
