### ISSUE TITLE
Membuat table berhasil, tapi untuk file di migration/badaso tidak ikut terbuat 

### ISSUE THREAD

**Issue by linxcodev** [uasoft-indonesia/badaso#605]
**Describe the bug**
Saya membuat table di Database Management, table berhasil dibuat di mysql, tetapi untuk file migrationya tidak ikut terbuat di folder migration/badaso, sedangkan di tutrial ke 3 muncul filenya. 

link tutrial :
https://www.youtube.com/watch?v=pUA9Sk16L68&list=PLO-UCDr2KEwPZPeQvjLmj-RVfNHycttPl&index=3

**Screenshots**

![Cuplikan layar dari 2022-03-04 22-24-37](https://user-images.githubusercontent.com/22840352/156791914-0ec22c66-f913-4e39-942d-7d5116376b4a.png)

![Cuplikan layar dari 2022-03-04 22-25-12](https://user-images.githubusercontent.com/22840352/156792129-658872ee-ecf8-4acc-a834-629046c79712.png)

![Cuplikan layar dari 2022-03-04 22-32-21](https://user-images.githubusercontent.com/22840352/156792418-930333c9-8bd6-467e-beb3-c6d3f2b39195.png)

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 20
 - Browser chrome

**Comment by rizkiheryandi** [comment]
Make sure your webserver has write permission on the migration folder
