### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by asyad85** [uasoft-indonesia/badaso#613]
Saya coba install badaso menggunakan Git, composer 2.19, PHP 7.2, node.js 15.x, dengan perintah composer create-project badaso/starter your_project_name, tp muncul pesan seperti ini

[InvalidArgumentException]                                                    
Could not find package badaso/starter with stability stable in a version installable using your PHP version, PHP extensions and Composer version.

gimana solusinya mas, tks

**Comment by rizkiheryandi** [comment]
minimum php shoud be PHP 8

btw you can install badaso to laravel manually, because there's a bug on badaso starter and we are fixing it now

https://badaso-docs.uatech.co.id/getting-started/installation#on-existing-project

**Comment by rizkiheryandi** [comment]
Error on badaso starter already fix on latest version, so we can install it with starter https://badaso-docs.uatech.co.id/getting-started/installation#on-fresh-project
