### ISSUE TITLE
Display/Hide Columns

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#620]
**Wish**

Should be good to be able to display or hide column with a checkbox, like this

https://ibb.co/7t2J69h

**Usage**

- useful when the table has many columns
- for communication purpose

**Proposed solution**

- BadasoShow.vue : a new component
```
<template>
        <table>
              <slot name="thead2"></slot>
            </tr>
        </table>
</template>
```

- in browse.vue
   - data: () => ({
`    checkBox1: [],  or [0,1,1] to hide id and show 2 first columns at page load`
```  
<div slot="header">
              <h3> {{ dataType.displayNameSingular }}</h3>
            </div>
            <div>
              <badaso-show> 
                <template slot="thead2">
                  <th
                    v-for="(dataRow, index) in dataType.dataRows"
                    v-if="dataRow.browse == 1"
                    :key="index"
                    :sort-key="$caseConvert.stringSnakeToCamel(dataRow.field)"
                  >
                    <vs-checkbox
                      v-model=checkBox1[index]
                      size="small"
                    />
                    {{ dataRow.displayName }}   
                </th>
              </template>
            </badaso-show>
```

```
   <template slot="thead">
                  <vs-th
                    v-for="(dataRow, index) in dataType.dataRows"
                    v-if="(dataRow.browse == 1) && (checkBox1[index] == 1)" 
```
```
                        v-for="(dataRow, indexColumn) in dataType.dataRows"
                        v-if="(dataRow.browse == 1) && (checkBox1[indexColumn] == 1)"`
```

**Still to do**
Ideally we should have another field in bread (for instance Show) to display, if true, the column at the page load.

**Comment by rizkiheryandi** [comment]
> https://pasteboard.co/kmfXoZKEIUUr.png

The provided link 404 (not found)

**Comment by Dri372** [comment]
Sorry,

an ewe on 

https://ibb.co/7t2J69h

**Comment by rizkiheryandi** [comment]
This feature already in CRUD configuration, you can check/un-check the "browse" option

![image](https://user-images.githubusercontent.com/25028868/159787416-afd5b0f7-248c-43cc-852b-d7d7b5710892.png)

**Comment by Dri372** [comment]
Not at all.

The browse option is an admin setup (config of the crud) that display or hide fields permanently for this crud.

The proposed improvement is a user / real time option.
