### ISSUE TITLE
Error when Create Table Relation

### ISSUE THREAD

**Issue by ritaoktaviani07** [uasoft-indonesia/badaso#631]
**Describe the bug**
Error when Create Table Relation

**To Reproduce**
1. Create Table Kategori, Penerbit and Rak
2. Create a Relationship on the "Rak Table" 

**Expected behavior**
- On the "Rak table" there is a column "Kategori_id" that is relation to the "Kategori table"
- And relationship for table "Kategory_id" when we select the type "On Delete Restrict" and "On Update Cascade" will display a Danger 
- Then when we save again the table will display "Table already" and the Migration is still there

**Screenshots**
![1](https://user-images.githubusercontent.com/77379201/158500660-2f8ef4ce-2cc3-4a40-9d67-a12dbc488c9c.PNG)

**Comment by nawiq7208** [comment]
i think the issue was clear, the foreign key constraint so delete action was restrict on update cascade
