### ISSUE TITLE
Crud not show in API Documentation

### ISSUE THREAD

**Issue by abayzv** [uasoft-indonesia/badaso#680]
![image](https://user-images.githubusercontent.com/85657385/160321138-76a04757-5362-4f68-b1ed-5f600858458e.png)

i create new crud, in version 2.4.2 API documentation will generate
and the server default is my.default-host.com, where i can change this?

**Comment by rizkiheryandi** [comment]
You can see the config of swagger in `config/l5-swagger.php`

For more detail, you can see here https://github.com/DarkaOnLine/L5-Swagger

Btw, i think you can update badaso to the latest version for better result too, badaso lestst version already in 2.4.11 

Thank you

**Comment by abayzv** [comment]
thanks, its work, just use this code in terminal, and its working fine,
`$ php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`
`$ php artisan l5-swagger:generate`
