### ISSUE TITLE
Error unsetting switch component

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#702]
**Describe the bug**
No possibility to unset a switch component

**To Reproduce**

Create a simple table/crud with a bolean (tiny int) type / switch component.
You cannot add a record with this unset
You can add a row if you set On this field, but
You cannot edit the record and unset the field.

**Comment by miftahurrahmi** [comment]
success add data type switch for value 1 or 0, but cannot edit data type switch from 1 to 0
![image](https://user-images.githubusercontent.com/60600153/231634249-6147d023-2544-4723-9510-9a697616a343.png)
