### ISSUE TITLE
[Question] - How to make dependent vue component?

### ISSUE THREAD

**Issue by sujit-baniya** [uasoft-indonesia/badaso#717]
While adding the data from custom `add.vue`, I wanted to calculate values to a component. 

For e.g., When user choose an item from dropdown and select amount, then I wanted to calculated the commission rate and put to the component.

![image](https://user-images.githubusercontent.com/4959215/175879786-4f2b92c8-c00f-44e2-8c0c-3ff07f1b8eb3.png)

**Comment by rahmatalmubarak** [comment]
You can see how to make a component in badaso documentation [https://badaso-docs.uatech.co.id/id/customization/custom-component](url)

**Comment by sujit-baniya** [comment]
@rahmatalmubarak The link you've provided is leading to issues
