### ISSUE TITLE
Multiple relation on same table 

### ISSUE THREAD

**Issue by tioagustian** [uasoft-indonesia/badaso#719]
Multiple realtion on same table showing only one relation
I have 2 field wich contains user_id and checker_id field, both of fields is related to user table. But when i create CRUD with multiple relation, both of fields showing same relation value even they have different id.
![image](https://user-images.githubusercontent.com/22042878/178202904-66ac2ffc-cc4d-4c0d-828a-874b75121fbe.png)
![image](https://user-images.githubusercontent.com/22042878/178202956-11ce28e3-4e00-4d96-95f7-965d698ffb2b.png)

**Comment by rahmatalmubarak** [comment]
what should show in your table? can you tell what your choicee for teacher field and user field

**Comment by TioA** [comment]
I want to show badaso_users.name from each column. But both display the same name from badaso users table

**Comment by MuhammadBobbi** [comment]
> I want to show badaso_users.name from each column. But both display the same name from badaso users table

yes we know you wanna set relation to badaso users table, but @rahmatalmubarak asking what your choice for checker id and teacher id, so we can try to reproduce your bug 

thank you
