### ISSUE TITLE
Component « Upload File » - delete does not work

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#721]
**Describe the bug**
    • With the composant »Upload File » you can upload a file and update the db field with the path.
    • Then you can edit this row and choose to delete it. On the edit modal, the field get blank but after updating the record, the field is unchanged.

**Comment by rizkiheryandi** [comment]
what is composant ?

please include with the screenhoot too if possible

thank you

**Comment by Dri372** [comment]
The crud https://ibb.co/dMTQcH7
Initial Browse https://ibb.co/Wc2Zh5g
Edit https://ibb.co/HdHdjWP
Edit after deletion https://ibb.co/QDDRq62
Browse after update https://ibb.co/KDzZDg7

You can see on the last image that the field is not erased (same data as Initial Browse)

**Comment by miftahurrahmi** [comment]
component upload file get error when doing process edit data
1. create database, add field type text
2. create crud management, set data type as upload file
3. add new data table for upload file
4. doing process edit data, delete data column upload file and let it blank. then save
5. see the error. data can't success delete
