### ISSUE TITLE
Impossible to remove all permission of a role

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#722]
**Describe the bug**
You  cannot remove all permission of a role, you have to let one.

**To Reproduce**
    • Fresh Badaso install
    • Customer rôle has no permission
    • create one permission
    • save
    • try to remove the permission → Danger msg
         
**Enhancement**
    • Have a config option to not attach the rôle customer to a new registered user.

**Comment by rizkiheryandi** [comment]
Whats the point for remove all permission of the role ?

For now

Just remove all permission for the customer role if you dont wanna customer have a permission

you also can rename the customer role if you want too

**Comment by Dri372** [comment]
> Whats the point for remove all permission of the role ?

See my post "To reproduce"

Cause of the problem
file : BadasoRolePermissionController.php
method : addOrEdit
code :             $request->validate([
                 'permissions' => ['required'],   <--------- empty array -> field not present *

* https://laravel.com/docs/9.x/validation#rule-required
