### ISSUE TITLE
Component TextArea - can't erase

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#755]
**Describe the bug**
You can edit / change a textarea field but if you want to erase it (if you put nothing in the input) the field is unchanged.

**Comment by rizkiheryandi** [comment]
@Dri372 please always explain more detail about the issue, how to reproduce and what the expected, also please inlucde with screenshot if possible

1. is the field nullable or not ?
2. what happen, was validation requeired or success without change ?

**Comment by Dri372** [comment]
• Version 2.4.13 / db postgresql
How to reproduce
    • create a new table ‘cars’ with a nullable text field ‘model’
    • create a crud
    • Add a new record with model ‘m1’ : Ok
    • Edit this record ‘m1’ → ‘m2’ : Ok
    • Edit this record ‘m2’ → ‘’ : KO (Danger Msg : sql error : update cars set where id=1)
