### ISSUE TITLE
User can only see the data he created himself (permission management)

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso#846]
**Is your feature request related to a problem? Please describe.**
Add option to permission management, that a user can only access data that created by itself

**Comment by rahmatalmubarak** [comment]
1. Buat input select multiple untuk memilih role yang dapat melihat seluruh data (default user hanya dapat meilihat data yang dibuat sendiri)
2. Buat input select untuk memilih field database sebagai identifikasi data user mana yang memilki data terkait
3. Buat input di edit permission
