### ISSUE TITLE
License Key: where get it?

### ISSUE THREAD

**Issue by APMU** [uasoft-indonesia/badaso#921]
Hi Guys,

On DOCs says: "_Before develop Badaso, please get BADASO_LICENSE_KEY by register on [Badaso](https://badaso.uatech.co.id/) or contact badaso core team. This key must be included in the laravel project's .env. Steps for registering and getting a license on Badaso Dashboard can be found on [Badaso Docs](https://badaso-docs.uatech.co.id/docs/en/getting-started/installation/)._"

But, i don't find it on site OR how to get it.

How to get the LICENCE KEY?

Thanks!

**Comment by rizkiheryandi** [comment]
Now you don't need a license key to use badaso
