### ISSUE TITLE
Bugs "Attempt to read property \"roles\" on null" in api response when set permission to Is Public.

### ISSUE THREAD

**Issue by Fit-Developer** [uasoft-indonesia/badaso#977]
**Describe the bug**
I will get data from api without authorization. I have enabled Is Public in Permission Management. But When I call the api I got this error "Attempt to read property \"roles\" on null"

**To Reproduce**
1. Go to Permission Management
2. Click edit on brows permission
3. Enable Is Public
4. Call api
5. See error

**Expected behavior**
Lists of data without authorization.

**Screenshots**
1. Enable Is Public
![image](https://github.com/uasoft-indonesia/badaso/assets/124032007/1a5ec448-1aea-4ee3-a2d4-5910c6701b6a)

2. Error
![image](https://github.com/uasoft-indonesia/badaso/assets/124032007/72c3a754-0863-4059-8f4c-3cc97f008ad8)

**Badaso (please complete the following information):**
 - Version 2.9.4

**Comment by Fit-Developer** [comment]
it work properly, but it has error "Attempt to read property \"id\" on null" when I do with this tutorial 21. How To Only Show Data For Who Created The Data.

**Comment by miftahurrahmi** [comment]
please screenshot your error and write step until you get error when using tutorial  21. How To Only Show Data For Who Created The Data.

> it work properly, but it has error "Attempt to read property "id" on null" when I do with this tutorial 21. How To Only Show Data For Who Created The Data.
