### ISSUE TITLE
Storage Link on default badaso put wrong folder

### ISSUE THREAD

**Issue by Muhammad0Ali** [uasoft-indonesia/badaso#995]
**Describe the bug**
When using the upload image feature, the file path taken is wrong. By running the default artisan command "storage:link" the linked folder is "app/public", while badaso creates its own folder outside of the public folder. So the uploaded file will have an error taking the link on the storage.

**To Reproduce**
1. Go to 'Media manager'
2. Click on 'Image menu'
3. Click on 'plus icon'
4. Click on 'upload'
5. Click on 'chose file'
6. then upload image
7. See error (image broken)

**Expected behavior**
The images should be load and preview on page.

**Screenshots**
If applicable, add screenshots to help explain your [problem.](url)

<img width="1440" alt="Screenshot 2023-06-12 at 3 08 46 PM" src="https://github.com/uasoft-indonesia/badaso/assets/48522810/48441430-7181-4fb3-ac4a-fff77ce7f069">
<img width="1440" alt="Screenshot 2023-06-12 at 3 23 16 PM" src="https://github.com/uasoft-indonesia/badaso/assets/48522810/5a412c6f-e9e3-43c3-a617-403efe2f24d7">

**Badaso (please complete the following information):**
 - Version 2.9.6

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 114.0.5735.106

**Comment by rahmatalmubarak** [comment]
Hi,
To solve this problem, you can open the .env file and change the value of FILESYSTEM_DRIVER from local to public

**Comment by rizkiheryandi** [comment]
Close (no response from issue owner)
